
import React, { useState } from 'react';

interface PlanDisplayProps {
  content: string;
  onReset: () => void;
  title: string;
  onRegenerate?: (skippedMeals: string[]) => void;
  currentPlanType: 'diet' | 'workout';
  onCrossNavigate: (target: 'diet' | 'workout') => void;
}

const PlanDisplay: React.FC<PlanDisplayProps> = ({ content, onReset, title, onRegenerate, currentPlanType, onCrossNavigate }) => {
  const [skippedMeals, setSkippedMeals] = useState<string[]>([]);
  const [isDownloading, setIsDownloading] = useState(false);
  
  const handleDownload = () => {
    const element = document.getElementById('plan-content');
    if (!element) return;

    setIsDownloading(true);

    // Scroll to top to prevent canvas cropping issues on mobile
    window.scrollTo(0, 0);

    // Use html2pdf if available (loaded via CDN in index.html)
    // @ts-ignore
    if (typeof window.html2pdf !== 'undefined') {
       const opt = {
        margin:       [5, 5, 5, 5],
        filename:     'THE_GYM_CKBT_PLAN.pdf',
        image:        { type: 'jpeg', quality: 0.98 },
        html2canvas:  { 
          scale: 2, 
          useCORS: true, 
          letterRendering: true,
          scrollY: 0, // Critical for mobile
          windowWidth: document.documentElement.offsetWidth // Ensure captures full width
        },
        jsPDF:        { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };
      
      // @ts-ignore
      window.html2pdf().set(opt).from(element).save().then(() => {
        setIsDownloading(false);
      }).catch((err: any) => {
        console.error("PDF generation failed", err);
        setIsDownloading(false);
        alert("PDF generation failed on this device. Try taking a screenshot.");
      });
    } else {
      // Fallback to print
      window.print();
      setIsDownloading(false);
    }
  };

  const handleWhatsAppShare = () => {
    const message = `Hey! I just created a personalized diet/workout plan using THE GYM CKBT App.\n\nIt's amazing! You should try it too.`;
    const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank');
  };

  const toggleSkipMeal = (meal: string) => {
    setSkippedMeals(prev => 
      prev.includes(meal) ? prev.filter(m => m !== meal) : [...prev, meal]
    );
  };

  const handleUpdate = () => {
    if (onRegenerate) {
      onRegenerate(skippedMeals);
    }
  };

  const possibleMeals = ['Breakfast', 'Lunch', 'Evening Snack', 'Dinner', 'Post Workout'];

  return (
    <div className="bg-white rounded-lg shadow-xl border border-gray-100 print-content">
      
      {/* Interactive Header - Hidden in Print */}
      <div className="bg-red-600 p-6 text-white flex flex-row justify-between items-center sticky top-0 z-10 no-print shadow-md rounded-t-lg">
        <h2 className="text-xl md:text-2xl font-extrabold tracking-tight">{title}</h2>
        
        <button 
          onClick={onReset}
          className="bg-white text-red-600 px-4 py-2 rounded-full font-bold text-sm hover:bg-gray-100 transition-colors shadow-sm"
        >
          New Plan
        </button>
      </div>

      {/* Plan Content Area - This is what gets printed/downloaded */}
      <div className="p-4 md:p-12 bg-white min-h-[500px]" id="plan-content">
        
        {/* Company Header - Always visible in the plan view/pdf */}
        <div className="text-center border-b-4 border-red-600 pb-6 mb-8">
          <h1 className="text-3xl md:text-4xl font-extrabold text-red-700 uppercase tracking-tighter">THE GYM CKBT</h1>
          <div className="mt-2 text-gray-600 font-medium space-y-1 text-sm md:text-base flex flex-col items-center">
            <a 
              href="https://www.google.com/maps/search/?api=1&query=2442+WWH,+Unnamed+Road,+Chakarbhatha,+Chhattisgarh+495220"
              target="_blank"
              rel="noopener noreferrer"
              className="group hover:text-red-700 transition-colors cursor-pointer flex items-center gap-1"
            >
              <span>📍</span>
              <span className="group-hover:underline">Behind Sarkari Hospital, Main Road, CKBT BSP</span>
            </a>
            <p>📞 Contact: 7000142415</p>
          </div>
        </div>

        {/* Render the HTML directly - Gemini generated HTML with Tailwind classes */}
        <div 
          className="prose prose-red max-w-none text-gray-800"
          dangerouslySetInnerHTML={{ __html: content }}
        />

        {/* Footer for PDF */}
        <div className="mt-12 pt-6 border-t border-gray-200 text-center text-gray-500 text-xs md:text-sm">
          <p>Generated by THE GYM CKBT App. Train Hard, Stay Consistent.</p>
        </div>
      </div>

      {/* CROSS NAVIGATION BUTTON (Placed as requested) */}
      <div className="bg-red-50 p-6 flex flex-col items-center gap-3 no-print border-t border-gray-100">
         <p className="text-red-800 font-bold text-sm uppercase tracking-wide">
           {currentPlanType === 'diet' ? 'Complete your routine:' : 'Optimize your results:'}
         </p>
         <button 
           onClick={() => onCrossNavigate(currentPlanType === 'diet' ? 'workout' : 'diet')}
           className="w-full sm:w-auto bg-white text-red-600 border-2 border-red-600 px-8 py-3 rounded-full font-extrabold text-lg hover:bg-red-600 hover:text-white transition-all transform hover:-translate-y-1 shadow-md flex items-center justify-center gap-2"
         >
           {currentPlanType === 'diet' ? '🏋️ Generate Workout Plan' : '🥗 Generate Diet Plan'}
           <span>→</span>
         </button>
      </div>

      {/* ACTION BUTTONS: Download PDF & Share (Below Content) */}
      <div className="bg-white p-6 flex flex-col items-center gap-4 no-print">
          <div className="flex flex-col sm:flex-row gap-4 w-full justify-center">
            <button 
              onClick={handleDownload}
              disabled={isDownloading}
              className={`
                w-full sm:w-auto flex items-center justify-center gap-2 px-6 py-3 rounded-xl font-bold transition-colors shadow-lg transform active:scale-95
                ${isDownloading ? 'bg-gray-400 cursor-wait' : 'bg-red-800 hover:bg-red-900 text-white'}
              `}
            >
              <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              {isDownloading ? 'Generating PDF...' : 'Download PDF'}
            </button>

            <button 
              onClick={handleWhatsAppShare}
              className="w-full sm:w-auto flex items-center justify-center gap-2 bg-green-500 text-white px-6 py-3 rounded-xl font-bold hover:bg-green-600 transition-colors shadow-lg transform active:scale-95"
            >
              <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" viewBox="0 0 16 16">
                <path d="M13.601 2.326A7.854 7.854 0 0 0 7.994 0C3.627 0 .068 3.558.064 7.926c0 1.399.366 2.76 1.057 3.965L0 16l4.204-1.102a7.933 7.933 0 0 0 3.79.965h.004c4.368 0 7.926-3.558 7.93-7.93A7.898 7.898 0 0 0 13.6 2.326zM7.994 14.521a6.573 6.573 0 0 1-3.356-.92l-.24-.144-2.494.654.666-2.433-.156-.251a6.56 6.56 0 0 1-1.007-3.505c0-3.626 2.957-6.584 6.591-6.584a6.56 6.56 0 0 1 4.66 1.931 6.557 6.557 0 0 1 1.928 4.66c-.004 3.639-2.961 6.592-6.592 6.592z"/>
              </svg>
              Share App
            </button>
          </div>
          
          <p className="text-xs text-gray-500 text-center max-w-sm">
            <span className="font-bold text-red-600">Note:</span> WhatsApp cannot directly attach website files. Please <strong>Download PDF</strong> first, then open your WhatsApp and send the file from your downloads.
          </p>
      </div>

      {/* Modify/Refine Section (Only for Diet Plans usually) - Hidden in Print */}
      {onRegenerate && (
        <div className="bg-gray-50 p-6 border-t-2 border-red-100 no-print">
          <h3 className="text-lg font-bold text-gray-800 mb-3">Refine Your Plan</h3>
          <p className="text-sm text-gray-600 mb-4">Want to skip a meal? Select below and we will regenerate the plan by redistributing the calories.</p>
          
          <div className="flex flex-wrap gap-3 mb-4">
            {possibleMeals.map(meal => (
              <label key={meal} className={`
                flex items-center space-x-2 px-4 py-2 rounded-full border cursor-pointer transition-colors text-sm font-semibold select-none
                ${skippedMeals.includes(meal) ? 'bg-red-100 border-red-500 text-red-700' : 'bg-white border-gray-200 text-gray-600 hover:bg-gray-100'}
              `}>
                <input 
                  type="checkbox" 
                  checked={skippedMeals.includes(meal)}
                  onChange={() => toggleSkipMeal(meal)}
                  className="hidden" 
                />
                <span>{skippedMeals.includes(meal) ? '✕' : ''} Skip {meal}</span>
              </label>
            ))}
          </div>
          
          <button 
            onClick={handleUpdate}
            disabled={skippedMeals.length === 0}
            className={`
              w-full md:w-auto px-6 py-2 rounded-lg font-bold transition-all shadow-md
              ${skippedMeals.length > 0 
                ? 'bg-gray-800 text-white hover:bg-black transform active:scale-95' 
                : 'bg-gray-200 text-gray-400 cursor-not-allowed'}
            `}
          >
            Update Plan
          </button>
        </div>
      )}

      {/* Footer Actions - Hidden in Print */}
      <div className="p-6 bg-gray-50 border-t flex justify-center no-print rounded-b-lg">
         <button 
          onClick={onReset}
          className="w-full md:w-auto bg-gray-800 text-white px-8 py-3 rounded-lg font-bold text-lg hover:bg-black transition-transform transform active:scale-95 shadow-lg"
        >
          Done
        </button>
      </div>
    </div>
  );
};

export default PlanDisplay;
